"""Esquema inicial de la Fase 1: user_preferences, weekly_editions y news_articles.

Revision ID: 9756e3dded6e
Revises: 
Create Date: 2026-09-22 05:10:58.280116
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9756e3dded6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_categories', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('include_animated_only', sa.Boolean(), nullable=False),
    sa.Column('max_articles', sa.Integer(), nullable=False),
    sa.Column('extra_preferences', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_articles >= 1', name=op.f('ck_user_preferences_max_articles_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences'))
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('weekly_editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='publication_status', native_enum=False, length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('week_end >= week_start', name=op.f('ck_weekly_editions_week_end_after_start')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_editions'))
    )
    with op.batch_alter_table('weekly_editions', schema=None) as batch_op:
        batch_op.create_index('ix_weekly_editions_status_week_start', ['status', 'week_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_editions_week_start'), ['week_start'], unique=False)
        batch_op.create_index('uq_weekly_editions_published_week', ['week_start', 'week_end'], unique=True, sqlite_where=sa.text("status = 'published'"), postgresql_where=sa.text("status = 'published'"))

    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('video_url', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('position >= 1', name=op.f('ck_news_articles_position_positive')),
    sa.ForeignKeyConstraint(['edition_id'], ['weekly_editions.id'], name=op.f('fk_news_articles_edition_id_weekly_editions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_articles')),
    sa.UniqueConstraint('edition_id', 'position', name='uq_article_position_per_edition')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_articles_category'), ['category'], unique=False)
        batch_op.create_index('ix_news_articles_edition_category', ['edition_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_edition_id'), ['edition_id'], unique=False)
        batch_op.create_index('ix_news_articles_edition_position', ['edition_id', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_published_at'), ['published_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_articles_language'))
        batch_op.drop_index('ix_news_articles_edition_position')
        batch_op.drop_index(batch_op.f('ix_news_articles_edition_id'))
        batch_op.drop_index('ix_news_articles_edition_category')
        batch_op.drop_index(batch_op.f('ix_news_articles_category'))

    op.drop_table('news_articles')
    with op.batch_alter_table('weekly_editions', schema=None) as batch_op:
        batch_op.drop_index('uq_weekly_editions_published_week', sqlite_where=sa.text("status = 'published'"), postgresql_where=sa.text("status = 'published'"))
        batch_op.drop_index(batch_op.f('ix_weekly_editions_week_start'))
        batch_op.drop_index('ix_weekly_editions_status_week_start')

    op.drop_table('weekly_editions')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))

    op.drop_table('user_preferences')
    # ### end Alembic commands ###
