"""Fase 2: campos de generacion automatica (IA/video) y tabla pipeline_runs.

Las columnas NOT NULL se anaden con ``server_default`` para que la migracion
funcione tambien sobre tablas que ya tienen noticias de la Fase 1.

Revision ID: 02044d2001b8
Revises: 9756e3dded6e
Create Date: 2026-09-22 13:22:35.223310
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '02044d2001b8'
down_revision: Union[str, None] = '9756e3dded6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'failed', 'skipped', name='pipeline_status', native_enum=False, length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=True),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('articles_created', sa.Integer(), nullable=False),
    sa.Column('articles_ai_written', sa.Integer(), nullable=False),
    sa.Column('videos_requested', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['weekly_editions.id'], name=op.f('fk_pipeline_runs_edition_id_weekly_editions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_edition_id'), ['edition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_status'), ['status'], unique=False)

    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('source_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('video_status', sa.Enum('not_requested', 'pending', 'processing', 'ready', 'failed', name='video_status', native_enum=False, length=20), nullable=False, server_default='not_requested'))
        batch_op.add_column(sa.Column('video_job_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ai_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.create_index(batch_op.f('ix_news_articles_video_status'), ['video_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_video_status'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('ai_model')
        batch_op.drop_column('video_job_id')
        batch_op.drop_column('video_status')
        batch_op.drop_column('source_name')
        batch_op.drop_column('summary')

    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_status'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_edition_id'))

    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
